apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: veridex-ingress
  namespace: veridex
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: api.veridex.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3000
    - host: app.veridex.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-dashboard
                port:
                  number: 3000
