export enum Permission {
  // Products
  VIEW_PRODUCTS = 'VIEW_PRODUCTS',
  CREATE_PRODUCTS = 'CREATE_PRODUCTS',
  UPDATE_PRODUCTS = 'UPDATE_PRODUCTS',
  DELETE_PRODUCTS = 'DELETE_PRODUCTS',
  MANAGE_PRODUCTS = 'MANAGE_PRODUCTS',
  VERIFY_PRODUCTS = 'VERIFY_PRODUCTS',

  // Documents
  VIEW_DOCUMENTS = 'VIEW_DOCUMENTS',
  UPLOAD_DOCUMENTS = 'UPLOAD_DOCUMENTS',
  UPDATE_DOCUMENTS = 'UPDATE_DOCUMENTS',
  DELETE_DOCUMENTS = 'DELETE_DOCUMENTS',
  VERIFY_DOCUMENTS = 'VERIFY_DOCUMENTS',

  // Compliance
  VIEW_COMPLIANCE = 'VIEW_COMPLIANCE',
  CREATE_COMPLIANCE = 'CREATE_COMPLIANCE',
  UPDATE_COMPLIANCE = 'UPDATE_COMPLIANCE',
  REVIEW_COMPLIANCE = 'REVIEW_COMPLIANCE',

  // Rules
  VIEW_RULES = 'VIEW_RULES',
  CREATE_RULES = 'CREATE_RULES',
  UPDATE_RULES = 'UPDATE_RULES',
  DELETE_RULES = 'DELETE_RULES',
  MANAGE_RULES = 'MANAGE_RULES',

  // Audits
  VIEW_AUDITS = 'VIEW_AUDITS',
  CREATE_AUDITS = 'CREATE_AUDITS',
  EXPORT_AUDITS = 'EXPORT_AUDITS',

  // Users
  VIEW_USERS = 'VIEW_USERS',
  CREATE_USERS = 'CREATE_USERS',
  UPDATE_USERS = 'UPDATE_USERS',
  DELETE_USERS = 'DELETE_USERS',
  MANAGE_USERS = 'MANAGE_USERS',

  // Organizations
  VIEW_ORGANIZATIONS = 'VIEW_ORGANIZATIONS',
  CREATE_ORGANIZATIONS = 'CREATE_ORGANIZATIONS',
  UPDATE_ORGANIZATIONS = 'UPDATE_ORGANIZATIONS',
  DELETE_ORGANIZATIONS = 'DELETE_ORGANIZATIONS',
  MANAGE_ORGANIZATIONS = 'MANAGE_ORGANIZATIONS',

  // Notifications
  VIEW_NOTIFICATIONS = 'VIEW_NOTIFICATIONS',
  CREATE_NOTIFICATIONS = 'CREATE_NOTIFICATIONS',
  UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS',

  // Settings
  VIEW_SETTINGS = 'VIEW_SETTINGS',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',

  // Admin
  ADMIN_ACCESS = 'ADMIN_ACCESS',
  SUPER_ADMIN_ACCESS = 'SUPER_ADMIN_ACCESS',
}
